/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    media: Media;
    organizations: Organization;
    'organization-memberships': OrganizationMembership;
    subscriptions: Subscription;
    'subscription-items': SubscriptionItem;
    'payment-attempts': PaymentAttempt;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      organizations: 'organization-memberships';
      subscriptions: 'subscriptions';
    };
    organizations: {
      subscriptions: 'subscriptions';
    };
    subscriptions: {
      items: 'subscription-items';
      payments: 'payment-attempts';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'organization-memberships': OrganizationMembershipsSelect<false> | OrganizationMembershipsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'subscription-items': SubscriptionItemsSelect<false> | SubscriptionItemsSelect<true>;
    'payment-attempts': PaymentAttemptsSelect<false> | PaymentAttemptsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Admin & {
    collection: 'admins';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Users synced from Clerk
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Clerk User ID for synchronization
   */
  clerkId: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Profile image URL from Clerk
   */
  imageUrl?: string | null;
  /**
   * Has the user verified their email address
   */
  emailVerified?: boolean | null;
  /**
   * Date when the email was verified
   */
  emailVerifiedAt?: string | null;
  /**
   * Phone number from Clerk
   */
  phoneNumber?: string | null;
  /**
   * Has the user verified their phone number
   */
  phoneVerified?: boolean | null;
  /**
   * Last sign-in timestamp from Clerk
   */
  lastSignInAt?: string | null;
  /**
   * Public metadata from Clerk
   */
  publicMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Organizations this user belongs to
   */
  organizations?: {
    docs?: (number | OrganizationMembership)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * User subscriptions
   */
  subscriptions?: {
    docs?: (number | Subscription)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships".
 */
export interface OrganizationMembership {
  id: number;
  /**
   * Clerk Membership ID for synchronization
   */
  clerkMembershipId: string;
  /**
   * The organization this membership belongs to
   */
  organization: number | Organization;
  /**
   * The user who is a member
   */
  user: number | User;
  /**
   * Role within the organization
   */
  role: 'org:admin' | 'org:member' | 'org:billing' | 'org:developer' | 'org:viewer';
  /**
   * Public metadata from Clerk
   */
  publicMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Private metadata from Clerk
   */
  privateMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  /**
   * Clerk Organization ID for synchronization
   */
  clerkId: string;
  name: string;
  /**
   * URL-friendly version of the organization name
   */
  slug?: string | null;
  /**
   * Organization logo/image URL from Clerk
   */
  imageUrl?: string | null;
  description?: string | null;
  /**
   * Maximum number of members allowed in this organization
   */
  maxAllowedMemberships?: number | null;
  /**
   * Public metadata from Clerk
   */
  publicMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Private metadata from Clerk
   */
  privateMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User who created this organization
   */
  createdBy?: (number | null) | User;
  /**
   * Organization subscriptions
   */
  subscriptions?: {
    docs?: (number | Subscription)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscription data synced from Clerk Billing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * Clerk Subscription ID for synchronization
   */
  clerkSubscriptionId: string;
  /**
   * Type of subscriber
   */
  subscriberType: 'user' | 'organization';
  /**
   * User subscriber (if subscriberType is user)
   */
  subscriberUser?: (number | null) | User;
  /**
   * Organization subscriber (if subscriberType is organization)
   */
  subscriberOrganization?: (number | null) | Organization;
  /**
   * Current subscription status
   */
  status: 'active' | 'past_due' | 'canceled' | 'incomplete' | 'incomplete_expired' | 'trialing' | 'unpaid';
  /**
   * Start of the current billing period
   */
  currentPeriodStart?: string | null;
  /**
   * End of the current billing period
   */
  currentPeriodEnd?: string | null;
  /**
   * Start of trial period
   */
  trialStart?: string | null;
  /**
   * End of trial period
   */
  trialEnd?: string | null;
  /**
   * Date when subscription was canceled
   */
  canceledAt?: string | null;
  /**
   * Whether to cancel at the end of the current period
   */
  cancelAtPeriodEnd?: boolean | null;
  /**
   * Additional metadata from Clerk
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Subscription items
   */
  items?: {
    docs?: (number | SubscriptionItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Payment attempts for this subscription
   */
  payments?: {
    docs?: (number | PaymentAttempt)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscription item details synced from Clerk Billing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-items".
 */
export interface SubscriptionItem {
  id: number;
  /**
   * Clerk Subscription Item ID for synchronization
   */
  clerkItemId: string;
  /**
   * Parent subscription
   */
  subscription: number | Subscription;
  /**
   * Plan identifier from Clerk
   */
  planId: string;
  /**
   * Human-readable plan name
   */
  planName?: string | null;
  /**
   * Number of units for this item
   */
  quantity?: number | null;
  /**
   * Price per unit in cents
   */
  unitAmount?: number | null;
  /**
   * Currency code (e.g., usd, eur)
   */
  currency?: string | null;
  /**
   * Billing interval
   */
  interval?: ('month' | 'year' | 'week' | 'day') | null;
  /**
   * Item status
   */
  status: 'active' | 'canceled' | 'upcoming' | 'ended' | 'abandoned' | 'incomplete' | 'past_due';
  /**
   * Additional metadata from Clerk
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment attempt records synced from Clerk Billing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts".
 */
export interface PaymentAttempt {
  id: number;
  /**
   * Clerk Payment Attempt ID for synchronization
   */
  clerkPaymentId: string;
  /**
   * Related subscription
   */
  subscription?: (number | null) | Subscription;
  /**
   * Payment amount in cents
   */
  amount: number;
  /**
   * Currency code (e.g., usd, eur)
   */
  currency: string;
  /**
   * Payment attempt status
   */
  status: 'succeeded' | 'failed' | 'processing' | 'requires_action' | 'requires_payment_method' | 'canceled';
  /**
   * Reason for payment failure
   */
  failureReason?: string | null;
  /**
   * Failure code from payment processor
   */
  failureCode?: string | null;
  /**
   * Related invoice ID from Stripe/payment processor
   */
  invoiceId?: string | null;
  /**
   * Charge ID from payment processor
   */
  chargeId?: string | null;
  /**
   * Type of payment method used (card, bank_transfer, etc)
   */
  paymentMethodType?: string | null;
  /**
   * When the payment was attempted
   */
  attemptedAt: string;
  /**
   * Additional metadata from Clerk
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'organization-memberships';
        value: number | OrganizationMembership;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'subscription-items';
        value: number | SubscriptionItem;
      } | null)
    | ({
        relationTo: 'payment-attempts';
        value: number | PaymentAttempt;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  imageUrl?: T;
  emailVerified?: T;
  emailVerifiedAt?: T;
  phoneNumber?: T;
  phoneVerified?: T;
  lastSignInAt?: T;
  publicMetadata?: T;
  organizations?: T;
  subscriptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  clerkId?: T;
  name?: T;
  slug?: T;
  imageUrl?: T;
  description?: T;
  maxAllowedMemberships?: T;
  publicMetadata?: T;
  privateMetadata?: T;
  createdBy?: T;
  subscriptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships_select".
 */
export interface OrganizationMembershipsSelect<T extends boolean = true> {
  clerkMembershipId?: T;
  organization?: T;
  user?: T;
  role?: T;
  publicMetadata?: T;
  privateMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  clerkSubscriptionId?: T;
  subscriberType?: T;
  subscriberUser?: T;
  subscriberOrganization?: T;
  status?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialStart?: T;
  trialEnd?: T;
  canceledAt?: T;
  cancelAtPeriodEnd?: T;
  metadata?: T;
  items?: T;
  payments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-items_select".
 */
export interface SubscriptionItemsSelect<T extends boolean = true> {
  clerkItemId?: T;
  subscription?: T;
  planId?: T;
  planName?: T;
  quantity?: T;
  unitAmount?: T;
  currency?: T;
  interval?: T;
  status?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts_select".
 */
export interface PaymentAttemptsSelect<T extends boolean = true> {
  clerkPaymentId?: T;
  subscription?: T;
  amount?: T;
  currency?: T;
  status?: T;
  failureReason?: T;
  failureCode?: T;
  invoiceId?: T;
  chargeId?: T;
  paymentMethodType?: T;
  attemptedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}